/* jshint node:true */

var path = require('path');

module.exports = function (grunt) {
	grunt.loadNpmTasks('grunt-ts');
	grunt.loadNpmTasks('grunt-peg');
	grunt.loadNpmTasks('grunt-wrap');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-contrib-clean');
	grunt.loadNpmTasks('intern-geezer');

	grunt.initConfig({
		// TODO: Always build, or never build, tests
		all: [ '**/*.ts', '!node_modules/**/*.ts', '!**/tests/integration/**' ],
		ignoreDefinitions: [ '<%= all %>', '!**/*.d.ts' ],

		clean: {
			framework: {
				src: [
					'**/*.js', '**/*.d.ts', '**/*.js.map', '!node_modules/**/*'
				],
				filter: function (filepath) {
					// Only clean the file if there is an associated .ts file
					var sourceFile = filepath.match(/(.*)\.(?:js(?:\.map)?|d\.ts)$/)[1] + '.ts';

					return grunt.file.exists(filepath) && grunt.file.isFile(sourceFile);
				}
			},
			parser: {
				src: [
					'templating/html/peg/html.js*'
				]
			}
		},

		peg: {
			parser: {
				src: 'templating/html/peg/html.pegjs',
				dest: 'templating/html/peg/html.js.unwrapped.js',
				options: {
					allowedStartRules: ['Template', 'BoundText']
				}
			}
		},

		wrap: {
			parser: {
				src: [ 'templating/html/peg/html.js.unwrapped.js' ],
				dest: '.',
				expand: true,
				rename: function (dest, src) {
					return path.join(dest, src.replace(/\.unwrapped\.js$/, ''));
				},
				options: {
					indent: '  ',
					wrapper: [ 'define([\'require\', \'module\'], function (require, module) {\n', '\n});' ]
				}
			}
		},

		ts: {
			options: {
				target: 'es5',
				module: 'amd',
				sourceMap: true,
				noImplicitAny: true,
				fast: 'never'
			},
			framework: {
				src: [ '<%= ignoreDefinitions %>' ]
			}
		},

		watch: {
			ts: {
				files: [ '<%= all %>' ],
				tasks: [ 'ts:framework' ]
			},
			parser: {
				files: [ '<%= peg.parser.src %>' ],
				tasks: [ 'parser' ]
			}
		},

		intern: {
			runner: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local'
				}
			},
			templating: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/templating' ],
					reporters: [ 'console' ]
				}
			},
			templatingCoverage: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/templating' ],
					reporters: [ 'lcovhtml' ]
				}
			},
			binding: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/binding' ],
					reporters: [ 'console' ]
				}
			},
			bindingCover: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/binding' ],
					reporters: [ 'lcovhtml' ]
				}
			},
			ui: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/ui' ],
					reporters: [ 'console' ]
				}
			},
			uiCoverage: {
				options: {
					runType: 'runner',
					config: 'tests/intern-local',
					suites: [ 'mayhem/tests/ui' ],
					reporters: [ 'lcovhtml' ]
				}
			},
			data: {
				options: {
					config: 'tests/intern',
					suites: [ 'mayhem/tests/data' ]
				}
			},
			client: {
				options: {
					config: 'tests/mayhem.intern'
				}
			}
		}
	});

	grunt.registerTask('parser', [ 'peg:parser', 'wrap:parser', 'cleanupParser' ]);
	grunt.registerTask('cleanupParser', function () {
		// removes intermediate unwrapped file generated by pegjs
		if (grunt.file.isFile('templating/html/peg/html.js.unwrapped.js')) {
			grunt.file['delete']('templating/html/peg/html.js.unwrapped.js');
		}
	});
	grunt.registerTask('test', [ 'intern:client' ]);

	var previousForceState = grunt.option('force');
	grunt.registerTask('force', function (set) {
		if (set === 'on') {
			grunt.option('force', true);
		}
		else if (set === 'off') {
			grunt.option('force', false);
		}
		else if (set === 'restore') {
			grunt.option('force', previousForceState);
		}
	});

	grunt.registerTask('build', ['force:on', 'parser', 'force:restore', 'ts:framework']);
	grunt.registerTask('default', ['force:on', 'parser', 'ts:framework', 'force:restore', 'watch']);
};
