define([
	'./Renderers'
], function (Renderers) {

	function ProgramRender(program) {
		//	summary:
		//		Constructor for an object that manages the rendering of a list of AST nodes
		//	program:
		//		The list of AST nodes to be rendered

		var i = 0,
			Renderer,
			node,
			blocks = this.blocks = [];

		// walk the list of AST nodes and instantiate an appropriate renderer for each node.
		while ((node = program[i++])) {
			Renderer = Renderers[node.type];
			if (Renderer) {
				blocks.push(new Renderer(node));
			}
			else {
				console.warn('no renderer for', node.type, node);
			}
		}
	}

	ProgramRender.prototype = {
		constructor: ProgramRender,

		render: function () {
			//	summary:
			//		Invoke the renderers for each of the logic blocks associated with this program.
			//	returns: array
			//		The list of output generated by the program

			var blocks = this.blocks || [],
				output = [],
				i = 0,
				block;

			while ((block = blocks[i++])) {
				output.push(block.render.apply(block, arguments));
			}

			return output;
		},

		unrender: function () {

		},

		destroy: function () {

		}
	};

	return ProgramRender;
});